import '@testing-library/jest-dom';

// Mock IndexedDB for Dexie
import 'fake-indexeddb/auto';

// Mock Electron API
(window as any).electronAPI = {
  platform: 'win32',
  isElectron: true,
  apiKeyGet: vi.fn().mockResolvedValue(null),
  apiKeySet: vi.fn().mockResolvedValue({ success: true }),
  sentimentAnalyze: vi.fn().mockResolvedValue({
    level: 'low',
    score: 0.5,
    positiveProb: 0.5,
    negativeProb: 0.5,
    crisisProb: 0,
    keywords: [],
    needCloud: false,
    method: 'keyword',
    timestamp: Date.now(),
  }),
  sentimentGetModelStatus: vi.fn().mockResolvedValue({ onnxLoaded: false }),
  onSyncReceive: vi.fn().mockReturnValue(() => {}),
  onSyncStatusChanged: vi.fn().mockReturnValue(() => {}),
  onSetLanguage: vi.fn().mockReturnValue(() => {}),
  minimizeWindow: vi.fn(),
  maximizeWindow: vi.fn(),
  closeWindow: vi.fn(),
  isMaximized: vi.fn().mockResolvedValue(false),
  onMaximizeChange: vi.fn().mockReturnValue(() => {}),
  openExternal: vi.fn().mockResolvedValue({ success: true }),
  relaunch: vi.fn().mockResolvedValue(undefined),
  emotionAnalyzeDiary: vi.fn().mockResolvedValue({}),
  emotionAnalyzeConversation: vi.fn().mockResolvedValue({}),
  emotionCalculateHealthIndex: vi.fn().mockResolvedValue(75),
  emotionCalculateRiskLevel: vi.fn().mockResolvedValue('low'),
  emotionGenerateInsights: vi.fn().mockResolvedValue([]),
  emotionGenerateSuggestions: vi.fn().mockResolvedValue([]),
  behaviorAnalyzeDaily: vi.fn().mockResolvedValue({}),
  behaviorAnalyzeTrends: vi.fn().mockResolvedValue({}),
  behaviorGenerateSummary: vi.fn().mockResolvedValue(''),
  notificationSetReminders: vi.fn().mockResolvedValue({ success: true }),
  notificationGetReminders: vi.fn().mockResolvedValue([]),
  notificationAddReminder: vi.fn().mockResolvedValue({ success: true }),
  notificationRemoveReminder: vi.fn().mockResolvedValue({ success: true }),
  notificationToggleReminder: vi.fn().mockResolvedValue({ success: true }),
  notificationStartCheck: vi.fn().mockResolvedValue({ success: true }),
  notificationStopCheck: vi.fn().mockResolvedValue({ success: true }),
  notificationTest: vi.fn().mockResolvedValue({ success: true }),
  onNotificationSent: vi.fn().mockReturnValue(() => {}),
  removeNotificationSent: vi.fn(),
  startSyncServer: vi.fn().mockResolvedValue({ running: false }),
  stopSyncServer: vi.fn().mockResolvedValue({ success: true }),
  getSyncStatus: vi.fn().mockResolvedValue({ running: false }),
  removeSyncReceive: vi.fn(),
  removeSyncStatusChanged: vi.fn(),
  sentimentCloudAnalyze: vi.fn().mockResolvedValue(null),
  sentimentSetApiKey: vi.fn().mockResolvedValue({ success: true }),
  openDataFolder: vi.fn(),
};
